from app.models import db, Like, environment, SCHEMA
from sqlalchemy.sql import text


def seed_likes():
  like1 = Like(isLiked=True, song_id=1, user_id=2)
  like2 = Like(isLiked=True, song_id=1, user_id=13)
  like3 = Like(isLiked=True, song_id=1, user_id=15)
  like4 = Like(isLiked=True, song_id=2, user_id=9)
  like5 = Like(isLiked=True, song_id=2, user_id=10)
  like6 = Like(isLiked=True, song_id=2, user_id=11)
  like7 = Like(isLiked=True, song_id=2, user_id=12)
  like8 = Like(isLiked=True, song_id=2, user_id=13)
  like9 = Like(isLiked=True, song_id=2, user_id=1)
  like10 = Like(isLiked=True, song_id=3, user_id=5)
  like11 = Like(isLiked=True, song_id=3, user_id=7)
  like12 = Like(isLiked=True, song_id=3, user_id=8)
  like13 = Like(isLiked=True, song_id=3, user_id=9)
  like14 = Like(isLiked=True, song_id=3, user_id=15)
  like15 = Like(isLiked=True, song_id=4, user_id=14)
  like16 = Like(isLiked=True, song_id=4, user_id=6)
  like17 = Like(isLiked=True, song_id=4, user_id=5)
  like18 = Like(isLiked=True, song_id=4, user_id=1)
  like19 = Like(isLiked=True, song_id=4, user_id=2)
  like20 = Like(isLiked=True, song_id=5, user_id=17)
  like21 = Like(isLiked=True, song_id=5, user_id=18)
  like22 = Like(isLiked=True, song_id=5, user_id=13)
  like23 = Like(isLiked=True, song_id=5, user_id=12)
  like24 = Like(isLiked=True, song_id=5, user_id=11)
  like25 = Like(isLiked=True, song_id=6, user_id=12)
  like26 = Like(isLiked=True, song_id=6, user_id=17)
  like27 = Like(isLiked=True, song_id=6, user_id=1)
  like28 = Like(isLiked=True, song_id=6, user_id=3)
  like29 = Like(isLiked=True, song_id=6, user_id=5)
  like30 = Like(isLiked=True, song_id=6, user_id=7)

  db.session.add(like1)
  db.session.add(like2)
  db.session.add(like3)
  db.session.add(like4)
  db.session.add(like5)
  db.session.add(like6)
  db.session.add(like7)
  db.session.add(like8)
  db.session.add(like9)
  db.session.add(like10)
  db.session.add(like11)
  db.session.add(like12)
  db.session.add(like13)
  db.session.add(like14)
  db.session.add(like15)
  db.session.add(like16)
  db.session.add(like17)
  db.session.add(like18)
  db.session.add(like19)
  db.session.add(like20)
  db.session.add(like21)
  db.session.add(like22)
  db.session.add(like23)
  db.session.add(like24)
  db.session.add(like25)
  db.session.add(like26)
  db.session.add(like27)
  db.session.add(like28)
  db.session.add(like29)
  db.session.add(like30)

  db.session.commit()


def undo_likes():
  if environment == "production":
    db.session.execute(f"TRUNCATE table {SCHEMA}.likes RESTART IDENTITY CASCADE;")
  else:
    db.session.execute(text("DELETE FROM likes"))
      
  db.session.commit()